[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dynamate"
version = "0.1.0"
description = "Multi-agent framework for running molecular dynamics simulations"
authors = ["Cassandra Masschelein <cassandra.masschelein@epfl.ch>, Salomé Guilbert <salome.guilbert@epfl.ch>"]
readme = "README.md"
